import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/ui/footer/Footer";
import Navbar from "@/components/ui/navbar/Navbar";

const poppinsText = Poppins({
    weight: "400", 
  subsets:["latin"]
});

// const geistMono = Poppins({
//   variable: "--poppins",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Next App Base",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppinsText.className} antialiased mx-20`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
